# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"\xaa\x03\n\x04Item\x12\x14\n\x07item_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\titem_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\ritem_category\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\nitem_price\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x1a\n\ritem_quantity\x18\x05 \x01(\x05H\x04\x88\x01\x01\x12%\n\x0bitem_status\x18\x06 \x01(\x0e\x32\x0b.ItemStatusH\x05\x88\x01\x01\x12%\n\x0bitem_action\x18\x07 \x01(\x0e\x32\x0b.ActionTypeH\x06\x88\x01\x01\x12\x1f\n\x12item_status_change\x18\x08 \x01(\x08H\x07\x88\x01\x01\x12\x1c\n\x0fitem_price_drop\x18\t \x01(\x02H\x08\x88\x01\x01\x42\n\n\x08_item_idB\x0c\n\n_item_nameB\x10\n\x0e_item_categoryB\r\n\x0b_item_priceB\x10\n\x0e_item_quantityB\x0e\n\x0c_item_statusB\x0e\n\x0c_item_actionB\x15\n\x13_item_status_changeB\x12\n\x10_item_price_drop*0\n\nActionType\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02*O\n\nItemStatus\x12\x0c\n\x08IN_STOCK\x10\x00\x12\x10\n\x0cOUT_OF_STOCK\x10\x01\x12\x0f\n\x0b\x43OMING_SOON\x10\x02\x12\x10\n\x0c\x44ISCONTINUED\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONTYPE._serialized_start=448
  _ACTIONTYPE._serialized_end=496
  _ITEMSTATUS._serialized_start=498
  _ITEMSTATUS._serialized_end=577
  _ITEM._serialized_start=20
  _ITEM._serialized_end=446
# @@protoc_insertion_point(module_scope)
