# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"\xbe\x04\n\x05Order\x12\x15\n\x08order_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07user_id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1a\n\rcustomer_name\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1b\n\x0e\x63ustomer_email\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x1c\n\x0f\x63ustomer_cellno\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1d\n\x10\x63ustomer_address\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x17\n\nproduct_id\x18\x07 \x01(\x05H\x06\x88\x01\x01\x12\x1a\n\rproduct_price\x18\x08 \x01(\x02H\x07\x88\x01\x01\x12\x1b\n\x0eorder_quantity\x18\t \x01(\x05H\x08\x88\x01\x01\x12-\n\x0corder_status\x18\n \x01(\x0e\x32\x12.order.OrderStatusH\t\x88\x01\x01\x12\x18\n\x0border_total\x18\x0b \x01(\x02H\n\x88\x01\x01\x12+\n\x0bitem_action\x18\x0c \x01(\x0e\x32\x11.order.ActionTypeH\x0b\x88\x01\x01\x42\x0b\n\t_order_idB\n\n\x08_user_idB\x10\n\x0e_customer_nameB\x11\n\x0f_customer_emailB\x12\n\x10_customer_cellnoB\x13\n\x11_customer_addressB\r\n\x0b_product_idB\x10\n\x0e_product_priceB\x11\n\x0f_order_quantityB\x0f\n\r_order_statusB\x0e\n\x0c_order_totalB\x0e\n\x0c_item_action*`\n\x0bOrderStatus\x12\x07\n\x03NEW\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tCONFIRMED\x10\x02\x12\x0b\n\x07SHIPPED\x10\x03\x12\r\n\tCOMPLETED\x10\x04\x12\r\n\tCANCELLED\x10\x05*0\n\nActionType\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERSTATUS._serialized_start=599
  _ORDERSTATUS._serialized_end=695
  _ACTIONTYPE._serialized_start=697
  _ACTIONTYPE._serialized_end=745
  _ORDER._serialized_start=23
  _ORDER._serialized_end=597
# @@protoc_insertion_point(module_scope)
