# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\xa5\x01\n\x14PaymentStatusMessage\x12\x12\n\npayment_id\x18\x01 \x01(\x05\x12\x10\n\x08order_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12&\n\x06status\x18\x04 \x01(\x0e\x32\x16.payment.PaymentStatus\x12\x16\n\x0etransaction_id\x18\x05 \x01(\t\x12\x16\n\x0e\x66\x61ilure_reason\x18\x06 \x01(\t*6\n\rPaymentStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\x0b\n\x07PENDING\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYMENTSTATUS._serialized_start=194
  _PAYMENTSTATUS._serialized_end=248
  _PAYMENTSTATUSMESSAGE._serialized_start=27
  _PAYMENTSTATUSMESSAGE._serialized_end=192
# @@protoc_insertion_point(module_scope)
